vim.cmd("highlight clear")
vim.g.colors_name = "ghostty"

local function hi(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

-- Editor
hi("Normal",       { ctermfg = 7,  ctermbg = 0 })
hi("NormalNC",     { ctermfg = 7,  ctermbg = 0 })
hi("LineNr",       { ctermfg = 8 })
hi("CursorLine",   { ctermbg = 0 })
hi("CursorLineNr", { ctermfg = 7,  cterm = { bold = true } })
hi("SignColumn",   { ctermbg = 0 })
hi("ColorColumn",  { ctermbg = 8 })
hi("VertSplit",    { ctermfg = 8 })
hi("StatusLine",   { ctermfg = 7,  ctermbg = 8 })
hi("StatusLineNC", { ctermfg = 8,  ctermbg = 0 })
hi("Pmenu",        { ctermfg = 7,  ctermbg = 8 })
hi("PmenuSel",     { ctermfg = 0,  ctermbg = 4 })
hi("PmenuSbar",    { ctermbg = 8 })
hi("PmenuThumb",   { ctermbg = 7 })
hi("Visual",       { ctermbg = 8 })
hi("Search",       { ctermfg = 0,  ctermbg = 3 })
hi("IncSearch",    { ctermfg = 0,  ctermbg = 11 })
hi("MatchParen",   { ctermfg = 6,  cterm = { bold = true } })
hi("NonText",      { ctermfg = 8 })
hi("SpecialKey",   { ctermfg = 8 })
hi("Folded",       { ctermfg = 8,  ctermbg = 0 })
hi("WildMenu",     { ctermfg = 0,  ctermbg = 4 })

-- Syntax
hi("Comment",      { ctermfg = 8,  cterm = { italic = true } })
hi("String",       { ctermfg = 2 })
hi("Keyword",      { ctermfg = 1 })
hi("Conditional",  { ctermfg = 1 })
hi("Repeat",       { ctermfg = 1 })
hi("Statement",    { ctermfg = 1 })
hi("Function",     { ctermfg = 4 })
hi("Identifier",   { ctermfg = 7 })
hi("Type",         { ctermfg = 6 })
hi("Constant",     { ctermfg = 5 })
hi("Number",       { ctermfg = 3 })
hi("Boolean",      { ctermfg = 3 })
hi("Operator",     { ctermfg = 7 })
hi("PreProc",      { ctermfg = 5 })
hi("Special",      { ctermfg = 6 })
hi("Underlined",   { cterm = { underline = true } })
hi("Error",        { ctermfg = 9,  ctermbg = 0 })
hi("Todo",         { ctermfg = 3,  cterm = { bold = true } })

-- Treesitter
hi("@variable",           { ctermfg = 7 })
hi("@variable.builtin",   { ctermfg = 5 })
hi("@function",           { ctermfg = 4 })
hi("@function.builtin",   { ctermfg = 6 })
hi("@function.call",      { ctermfg = 4 })
hi("@method",             { ctermfg = 4 })
hi("@method.call",        { ctermfg = 4 })
hi("@keyword",            { ctermfg = 1 })
hi("@keyword.return",     { ctermfg = 1 })
hi("@conditional",        { ctermfg = 1 })
hi("@repeat",             { ctermfg = 1 })
hi("@type",               { ctermfg = 6 })
hi("@type.builtin",       { ctermfg = 6 })
hi("@string",             { ctermfg = 2 })
hi("@number",             { ctermfg = 3 })
hi("@boolean",            { ctermfg = 3 })
hi("@constant",           { ctermfg = 5 })
hi("@constant.builtin",   { ctermfg = 5 })
hi("@comment",            { ctermfg = 8,  cterm = { italic = true } })
hi("@operator",           { ctermfg = 7 })
hi("@punctuation",        { ctermfg = 7 })
hi("@property",           { ctermfg = 7 })
hi("@field",              { ctermfg = 7 })
hi("@parameter",          { ctermfg = 7 })
hi("@tag",                { ctermfg = 1 })
hi("@tag.attribute",      { ctermfg = 3 })

-- Diagnostics
hi("DiagnosticError",          { ctermfg = 1 })
hi("DiagnosticWarn",           { ctermfg = 3 })
hi("DiagnosticInfo",           { ctermfg = 4 })
hi("DiagnosticHint",           { ctermfg = 8 })
hi("DiagnosticUnderlineError", { cterm = { underline = true }, ctermfg = 1 })
hi("DiagnosticUnderlineWarn",  { cterm = { underline = true }, ctermfg = 3 })
